############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "ERP"
url = "/erp"
weight = 3

[[main]]
weight = 4
name = "DevOps & SRE"


[[main]]
name = "Projects"
weight = 5

[[main]]
name = "Blog"
url = "/blog"
weight = 6

[[main]]
name = "Contact Us"
url = "/contact_us"
weight = 7


# devops & SRE submenu
[[main]]
parent = "DevOps & SRE"
name = "Observability"
url = "/observability"

[[main]]
parent = "DevOps & SRE"
name = "Cloud"
url = "/cloud"

[[main]]
parent = "DevOps & SRE"
name = "Self Managed"
url = "/on-prem"

# projects submenu
[[main]]
parent = "Projects"
name = "Real-estate ERPNext"
url = "/projects/real-estate-erpnext"
weight = 1

[[main]]
parent = "Projects"
name = "Web Portal + CRM ERPNext"
url = "/projects/3dscan-erpnext"
weight = 2

[[main]]
parent = "Projects"
name = "Opentelemetry, Signoz, CHDB"
url = "/projects/otel-sre"
weight = 3




# footer menu
[[footer]]
name = "Contact Us"
url = "/contact_us"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

